<?php

/**
 * Arreglos usados en carga de egresados: especialidades y rubros
 */

return [
    'tecnicos' => [
        'rubros' => null,
        'especialidades' => [
            'Tecnicatura en Aeronáutica',
            'Tecnicatura en Automotores',
            'Tecnicatura en Administración y Gestión de las Organizaciones',
            'Tecnicatura en Electrónica',
            'Tecnicatura en Electromecánica',
            'Tecnicatura en Química',
            'Tecnicatura en Informática Personal y Profesional',
            'Tecnicatura Maestro Mayor de obra'
        ]
    ],
    'oficios' => [
        'rubros' => [
            'Administración',
            'Agropecuario',
            'Artística',
            'Automotores',
            'Carpintería',
            'Comunicación e Idiomas',
            'Construcción, Instalaciones y Servicios',
            'Cuero y Calzado',
            'Electrónica y Electricidad',
            'Estética',
            'Gastronomía, Hoteleria y Turismo',
            'Industria Gráfica',
            'Industria Pesquera',
            'Industrias Plásticas',
            'Informática',
            'Metalmecánica y Metalurgia',
            'Minería',
            'Oficios Artesanales',
            'Refrigeración y Climatización',
            'Salud',
            'Seguridad e Higiene y Medioambiente',
            'Textil e Indumentaria'
        ],
        'especialidades' => [ // agrupadas por rubro
            'Administración' => [
                'Auxiliar Administrativo',
                'Auxiliar Contable',
                'Auxiliar Administrativo Contable de Pymes',
                'Auxiliar en Administración de microempresas',
                'Auxiliar Administrativo de Pymes',
                'Auxiliar en Administración y Conducción de RRHH',
                'Auxiliar en Marketing de Productos',
                'Auxiliar en Marketing de Servicios',
                'Auxiliar en Ventas',
                'Diseñador para la Exhibición de Productos',
                'Auxiliar en Liquidación de Impuestos',
                'Auxiliar en Liquidación de Sueldos y Jornales',
                'Operador de Software de Gestión Administrativo Contable',
                'Práctico Contable',
                'Auxiliar en Redacción Administrativa y Comercial',
                'Auxiliar en Relaciones públicas',
                'Vidrierista',
                'Portugués para Negocios Nivel I',
                'Portugués para Negocios Nivel II',
                'Operador de Autoelevador',
                'Inglés para Negocios Nivel I',
                'Inglés para Negocios Nivel II',
                'Francés para Negocios Nivel 1',
                'Francés para negocios Nivel 2',
                'Asistente de Estudio Jurídico y Notarial',
                'Capacitación en Planeamiento, organización y Gestión de Cooperativas',
                'Gerenciamiento de Empresas Unipersonales y Sociedades de Hecho',
                'Auxiliar en Gestión Previsional',
                'Elaborador de Alfajores Regionales',
            ],
            'Agropecuario' => [
                'Alambrador',
                'Avicultor',
                'Canalero',
                'Cestero',
                'Práctico en Clasificador de Cereales',
                'Práctico en Clasificador de Oleaginosas',
                'Criador Artificial de Abejas Reina',
                'Cultivador de Hongos Comestibles',
                'Cunicultor',
                'Embalador Hortícola',
                'Forestador',
                'Práctico en Huerta Bajo Nylon',
                'Práctico en injertos',
                'Inseminador artificial',
                'Jardinero',
                'Operador de moto sierras',
                'Operador de enfardadora',
                'Operador de máquina para aplicación de agroquímicos',
                'Operador de Silo- galpón Automatizado de puerto',
                'Podador',
                'Podador frutícola',
                'Horticultor',
                'Práctico en Sistemas de Riego por Aspersión',
                'Práctico en Sistemas de Riego por Gravedad',
                'Productor Biofertilizante',
                'Productor de Plantas de Interior',
                'Productor de Plantines de Frutilla',
                'Reparador de Molinos a Aguadas',
                'Tambero Ordeñador Mecánico',
                'Portugués para Ambitos Agropecuarios y Agroindustriales Nivel I',
                'Portugués para Ambitos Agropecuarios y Agroindustriales Nivel II',
                'Operario Apícola',
                'Asistente Apícola',
                'Apicultor',
                'Cosechador Fruti-hortíicola',
                'Embalador Frutícola',
                'Encargado de Cosecha Frutícola',
                'Encargado de Galpón de Empaque',
                'Raleador Frutícola',
                'Tractorista',
                'Inglés para Ambitos Agropecuarios y Agroindustriales Nivel I',
                'Inglés para Ambitos Agropecuarios y Agroindustriales Nivel II',
                'Francés para Ámbitos Agropecuarios y agroindustriales Nivel 1',
                'Francés para Ámbitos Agropecuarios y agroindustriales Nivel 2',
                'Petisero',
                'Operador de Cosechadora',
                'Operador de Sembradora',
                'Práctico en Manejo de Rodeos'
            ],
            'Artística' => [
                'Animador Sociocultural Artístico especializado en música',
                'Animador Sociocultural Artístico Especializado en Artes Visuales'
            ],
            'Automotores' => [
                'Chapista de Automotores',
                'Mecánico de Ciclomotores',
                'Mecánico de Frenos del Automotor',
                'Mecánico de Implementos Agrícolas',
                'Mecánico de Máquinas Viales',
                'Gomero Balanceador',
                'Pintor y Colorimetrista de automóviles',
                'Mecánico deTransmisiones',
                'Mecánico en Sistemas de Aire Acondicionado',
                'Práctico en Organización y Administración de Talleres de Automotores',
                'Electricista de Automotores',
                'Mecánico electrónico de Automotorers',
                'Mecánico Instalador de Equipos de GNC',
                'Auxiliar Mecánico de Automotores nafteros',
                'Auxiliar Mecánico de motores Diesel',
                'Cerrajero Automotor',
                'Mecánico de Tren delantero y Suspensión',
                'Mecánico de Sistemas de Encendido y Alimentación',
                'Auxiliar Mecánico de Automotores',
                'Mecánico de sistemas de inyección diesel',
                'Mecánica de Equipos y Sistemas Neumáticos',
                'Mecánica en Equipos y Sistemas Hidráulicos'
            ],
            'Carpintería' => [
                'Carpintero de banco',
                'Lustrador',
                'Práctico en Marquetería',
                'Práctico en Muebles Artesanales y Objetos Decorativos',
                'Remodelador de Muebles',
                'Reparador de Muebles',
                'Tornero de Madera',
                'Construcción de Muebles de Oficina',
                'Ebanista'
            ],
            'Comunicación e Idiomas' => [
                'Capacitación en Oratoria',
                'Interprete en Lenguas de señas',
                'Lecto-escritura Braille',
                'Recreación de Grupos',
                'Operador Sociocomunitario',
                'Inglés Nivel 5. B2.Nivel Intermedio 1',
                'Inglés Nivel 6. B2.Nivel Intermedio 2',
                'Comunicador para organizaciones sociales',
                'Portugués Nivel 1. A1. Principiante',
                'Portugués Nivel 2. A2. Elemental',
                'Portugués Nivel 3. B1. Nivel Preintermedio 1',
                'Portuguéss Nivel 4. B1. Nivel Preintermedio 2',
                'Portugués Nivel 5. B2. Nivel Preintermedio 1',
                'Portugués Nivel 6. B2. Nivel Preintermedio 2',
                'Inglés Nivel 1. A1. Nivel principiante',
                'Inglés Nivel 2. A2. Nivel elemental',
                'Inglés Nivel 3. B1. Nivel preintermedio 1',
                'Inglés Nivel 4. B1. Nivel preintermedio 2',
                'Francés Nivel 1 A1.Nivel principiante',
                'Francés Nivel 2 A2. Nivel elemental',
                'Francés Nivel 3 B1.Nivel preintermedio 1',
                'Francés Nivel 4 B1. Nivel preinterrmedio 2',
                'Francés Nivel 5 B2. Nivel intermedio 1',
                'Francés Nivel 6 B2. Nivel intermedio 2',
                'Portugués para Turismo Nivel I',
                'Portugués para Turismo Nivel II',
                'Portugués para Hotelería y Gastronomía Nivel I',
                'Portugués para Hotelería y Gastronomía Nivel II',
                'Inglés para Turismo Nivel I',
                'Inglés para Turismo Nivel II',
                'Inglés para Hotelería y gastronomía Nivel I',
                'Inglés para Hotelería y gastronomía Nivel II',
                'Francés para Turismo Nivel 1',
                'Francés para Turismo Nivel 2',
                'Francés para Hotelería y Gastronomía Nivel 1',
                'Francés para Hotelería y Gastronomía Nivel 2',
                'Portugués para Tecnología Digital Nivel I',
                'Portugués para Tecnología Digital Nivel II',
                'Inglés para Tecnología Digital Nivel I',
                'Inglés para Tecnología Digital Nivel II',
                'Frances para Tecnología Digital Nivel I',
                'Frances para Tecnología Digital Nivel II',
                'Portugués para Ambitos Técnicos e Industriales  Nivel I',
                'Portugués para Ambitos Técnicos e Industriales Nivel II',
                'Inglés para Ambitos Técnicos e Industriales  Nivel I',
                'Inglés para Ambitos Técnicos e Industriales Nivel II',
                'Francés para Ámbitos Técnicos e Industriales Nivel 1',
                'Francés para Ámbitos Técnicos e Industriales Nivel 2',
                'Portugués para el Sector Salud Nivel I',
                'Portugués para el Sector Salud Nivel II',
                'Francés para el Sector Salud Nivel 1',
                'Francés para el Sector Salud Nivel 2'
            ],
            'Construcción, Instalaciones y Servicios' => [
                'Colocador de Vidrios',
                'Colocador de Revestimiento Plástico',
                'Delineante Mecánico y de Obras Civiles',
                'Gasista 2ª Categoría - Res. 10430/93',
                'Gasista 3ª Categoría - Res. 10430/93',
                'Herrero de Obra',
                'Práctico en Mantenimiento de Edificios',
                'Operador de Moto niveladora',
                'Maquinista Vial',
                'Operador de Pala Cargadora',
                'Operador de topadora',
                'Operador de Tractor',
                'Pintor de Obra',
                'Prod. Ladrillo Suelo Cemento',
                'Yesero',
                'Zinguero',
                'Carpintero de Obra Fina',
                'Colocador de Placas de Roca de Yeso',
                'Oficial en Construcciones Industrializadas',
                'Electricista de Planta',
                'Instalador de Redes de Gas',
                'Instalador Sanitarista',
                'Operador de Máquinas viales',
                'Soldador Para la Construcción',
                'Techista',
                'Ceramista Industrial',
                'Cerrajero',
                'Armador y Carpintero de Hormigón Armado',
                'Albañil en Construcciones Tradicionales',
                'Colocador de Revestimientos de Base Húmeda'
            ],
            'Cuero y Calzado' => [
                'Auxiliar de Peletería',
                'Auxiliar en confección de Prendas de Cuero',
                'Auxiliar Marroquinero',
                'Tapicero',
                'Reparador de calzado',
                'Aparador de Calzado',
                'Armador de Calzado a Mano',
                'Centrador de Calzado a Máquina',
                'Cortador de Calzado',
                'Suelero de Calzado'
            ],
            'Electrónica y Electricidad' => [
                'Bobinador de máquinas eléctricas',
                'Montador Electricista - Res 2265/01',
                'Electricista Instalador - Res 2265/01',
                'Electricista Industrial',
                'Práctico en Automatización por Lógica Programada  (PLC)',
                'Reparador de Equipos Electrónicos Industriales',
                'Operador de Redes de Baja o Media Tensión',
                'Supervisión y Administración de Redes de Baja o Media Tensión',
                'Práctico en instalación de sistemas de energía solar',
                'Reparador de máquinas y Herramientas Eléctricas',
                'Reparador  Electrónico  de Audio y recepción de Radio',
                'Reparador de TV Cromático',
                'Reparador de Electrodomésticos',
                'Reparador de Equipos de Electro medicina',
                'Tendido de Redes Aéreas'
            ],
            'Estética' => [
                'Capacitación en Cosmetología',
                'Capacitación en Depilación',
                'Capacitación en Manicuría',
                'Peluquero Unisex',
                'Colorista y Peinador',
                'Permanentista'
            ],
            'Gastronomía, Hoteleria y Turismo' => [
                'Práctico en Conservación de Alimentos',
                'Elaborador de Alimentos a Base de Productos de Soja',
                'Elaborador de Queso Artesanal',
                'Manipulador de Alimentos',
                'Elaboración y Conservación de Carnes y Embutidos',
                'Elaboración y Conservación de Frutas y Hortalizas',
                'Auxiliar de Protocolo y Ceremonial',
                'Barman',
                'Cocinero para Restaurante Básico',
                'Cocinero para Restaurante Medio',
                'Cocinero para Restaurante Completo',
                'Cocinero de Fruto de Mar',
                'Cocinero para Comedor Escolar',
                'Confitero',
                'Coordinador Turístico',
                'Fideero',
                'Pizzero y Rotisero',
                'Mucama de Hotel',
                'Panadero',
                'Recepcionista y Conserje de Hotel',
                'Repostero Artesanal',
                'Práctico en Servicio de Buffet Frío',
                'Cheff',
                'Mozo Camarero de Salón',
                'Mozo Básico',
                'Ayudante Pastelería',
                'Oficial Facturero',
                'Oficial en Pastelería',
                'Pastelero Profesional',
                'Auxiliar de Somelier',
                'Práctico en organización de Eventos'
            ],
            'Industria Gráfica' => [
                'Impresor Off Set',
                'Tipógrafo',
                'Encuadernador',
                'Operador de Fotomecánica',
                'Práctico en Serigrafía',
                'Práctico en Diseño Gráfico de Sistemas Informáticos Nivel I',
                'Práctico en Diseño Gráfico de Sistemas Informáticos Nivel II',
                'Pintor Letrista',
                'Fotógrafo'
            ],
            'Industria Pesquera' => [
                'Filetero',
                'Portugués Para el Ambito naval Nivel I',
                'Portugués Para el Ambito naval Nivel II',
                'Electricista Naval',
                'Carpintero Naval',
                'Francés para el Ámbito Naval Nivel 1',
                'Francés para el Ámbito Naval Nivel 2',
                'Especialista en estructuras Navales',
                'Inglés para el Ámbito Naval  Nivel I',
                'Inglés para el Ámbito Naval  Nivel II',
                'Práctico en Procesamiento de Pescado',
                'Práctico en Control de Manufactura de Pescado'
            ],
            'Industrias Plásticas' => [
                'Práctico en Plástico Reforzado con Fibra de Vidrio',
                'Operador de Máquina Inyectora de Plástico',
                'Soldador Termoplástico'
            ],
            'Informática' => [
                'Diseño de Web',
                'Diseño Proyectual Asistido por Computadora',
                'Diseño Proyectual Asistido por Computadora Avanzado',
                'Operador de Sistema de Animación Computarizada',
                'Programador de Sistemas Informáticos Multimediales',
                'Programador de Sist. De Base de Datos de Computadoras Personales',
                'Programador de Sistemas Interfaces Gráficas',
                'Reparador de PC',
                'Instalador de Redes',
                'Supervisor de Redes ',
                'Operador de PC Bajo Entorno Gráfico',
                'Operador de PC con competencia en Procesador de textos, Planilla de Cálculo y Base de Datos',
                'Operador de Informática de Oficina'
            ],
            'Metalmecánica y Metalurgia' => [
                'Afilador de Herramientas',
                'Armador de Cerramientos de Aluminio',
                'Calderero',
                'Práctico en Carpintería Metálica',
                'Mecánico en Elementos de Ortopedia',
                'Mecánico Montador de Maquinarias',
                'Ajustador de Banco',
                'Modelista Mecánico',
                'Práctico en Punteado y Tratamiento de Chapa',
                'Relojero',
                'Soldador de Tuberías de Redes',
                'Soldador Oxiaciatilénico',
                'Soldador por Arco',
                'Soldador Variada',
                'Tornero',
                'Fresador',
                'Soldador básico',
                'Operador de Horno con Fusión y Colada de Acero Fundido en Horno Eléctrico por Arco e Inducción',
                'Operador de Torno CNC',
                'Cañista Montador',
                'Matricería',
                'Soldador Equipo MIG',
                'Soldador Equipo TIG',
                'Operador de Fresa CNC'
            ],
            'Minería' => [
                'Perforista Minero'
            ],
            'Oficios Artesanales' => [
                'Soguero',
                'Tejedor de telar',
                'Práctico en Construcción  de Muebles de Caña',
                'Práctico en construcción de Alhajas de Metales',
                'Confeccionista en Artesanías en Cerámica Fría para Souvenir y Decoración',
                'Confeccionista de Bijouterie',
                'Cartonería'
            ],
            'Refrigeración y Climatización' => [
                'Reparador de Refrigeradores Domésticos',
                'Reparador de Acondicionadores Aire individual',
                'Reparador de Heladeras Comerciales',
                'Reparador de Sistemas Eléctricos de Acondicionadores Centrales de Aire'
            ],
            'Salud' => [
                'Auxiliar en Atención al Público en Instituciones de Salud',
                'Operador Sociocomunitario especializado en atención de adicciones',
                'Auxiliar de Estadística de Salud',
                'Auxiliar en Cuidado de Adultos Mayores',
                'Auxiliar de Familia Especializado en Cuidado de Niños',
                'Auxiliar en Instituciones Educativas',
                'Mucama/o para establecimientos de salud-Familia Profesional: Salud y Ambiente.',
                'Limpieza y desinfección en establecimientos de salud- Familia Profesional: Salud y Ambiente.',
                'Auxiliar de familia especializado en cuidados de personas con discapacidad. Familia Profesional: Salud y Ambiente.',
                'Auxiliar de Seguridad e Higiene y Medio Ambiente de Establecimientos de Salud',
                'Higiene y Bioseguridad en el Trabajo de los establecimientos de Salud',
                'Auxiliar Odontológico',
                'Auxiliar en Enfermería',
                'Auxiliar en saneamiento Ambiental',
                'Inglés para el Sector Salud Nivel I',
                'Inglés para el Sector Salud Nivel II',
                'Protésico Dental de Laboratorio',
                'Acompañante Terapeutico'
            ],
            'Seguridad e Higiene y Medioambiente' => [
                'Administrador General del Medio Ambiente',
                'Apoyo en Seguridad e Higiene Industrial',
                'Ayudante en Seguridad e Higiene Industrial',
                'Guardavidas',
                'Controlador de Admisión y Permanencia',
                'Limpieza Institucional'
            ],
            'Textil e Indumentaria' => [
                'Modista de Alta Costura',
                'Bolsillero',
                'Cosedor a Mano y a Máquina',
                'Camisero',
                'Confeccionista de Bolsos y Mochilas',
                'Confeccionista de Faldas',
                'Confeccionista de Lencería y Corsetería',
                'Confeccionista de Ropa Blanca',
                'Confeccionista de Ropa Informal y Deportiva',
                'Confeccionista por Talle con Orientación Industrial',
                'Patronista y Cosedor de Camperas',
                'Cosedor de Ropa de Trabajo y Uniformes',
                'Práctico en Diseño Básico de Indumentaria',
                'Estampador Múltiple',
                'Modista',
                'Modista por Talle',
                'Operador de Máquina de Collareta',
                'Operador de Máquina Overlock',
                'Pantalonero',
                'Patronista y Confeccionista de Ropa de Bebe',
                'Patronista y Cortador de lencería',
                'Patronista y Cortador de Prendas de Punto',
                'Remallador',
                'Práctico en Revisión y Terminado de Prendas'
            ]
        ]
    ]
];
